version: '3.4'

services:
  fluent:
    build:
      context: ./docker/fluent
      target: forward
    container_name: fn-fluent
    image: fn-fluent:0.1.0
    ports:
      - 24224:24224
  fluent-bit:
    build:
      context: ./docker/fluent-bit
      target: forward
    container_name: fn-fluent-bit
    image: fn-fluent-bit:0.1.0
    ports:
      - 24225:24225
  fluent-secure:
    build: 
      context: ./docker/fluent
      target: forward-secure
    container_name: fn-fluent-secure
    image: fn-fluent-secure:0.1.0
    ports:
      - 24226:24226
  fluent-bit-secure:
    build:
      context: ./docker/fluent-bit
      target: forward-secure
    container_name: fn-fluent-bit-secure
    image: fn-fluent-bit-secure:0.1.0
    ports:
      - 24227:24227
